#!/usr/local/bin/node

const { stringToHex } = require('web3-utils')
const { executeMethod } = require('./lib')(process.argv[6])

if (process.argv.length !== 7) {
  console.error(`emittor service task nbrVerifier inputsInJSON privatekey`)
  process.exit(-1)
}

const serviceId = process.argv[2]
const task = process.argv[3]
const nbrVerfiers = process.argv[4]
const inputs = JSON.parse(process.argv[5])

executeMethod('create', [
  serviceId,
  stringToHex(task),
  stringToHex(JSON.stringify(inputs)),
  nbrVerfiers
])
  .then(console.log)
  .catch(console.error)
