#!/usr/local/bin/node

const { stringToHex } = require('web3-utils')
const { executeMethod } = require('./lib')(process.env.PRIVATE_KEY)

if (process.argv.length !== 7) {
  console.error(`emittor service task "{\\"inputA\\": 42}" 0x 0x,0x,0x`)
  process.exit(-1)
}

const service = process.argv[2]
const task = process.argv[3]
const inputs = JSON.parse(process.argv[4])
const submitter = process.argv[5]
const verifiers = process.argv[6].split(',')

executeMethod('create', [
  stringToHex(service),
  stringToHex(task),
  stringToHex(JSON.stringify(inputs)),
  submitter,
  verifiers,
  verifiers.length
])
  .then(console.log)
  .catch(console.error)
