#!/usr/local/bin/node

const { execute } = require('./lib')(process.argv[4])

if (process.argv.length !== 5) {
  console.error(`executor service task privatekey`)
  process.exit(-1)
}

const service = process.argv[2]
const task = process.argv[3]

execute(service, task, async inputs => inputs.a + inputs.b)

console.log('executor listening...')
