#!/usr/local/bin/node

const { verify } = require('./lib')(process.argv[4])

if (process.argv.length !== 5) {
  console.error(`validator service task privatekey`)
  process.exit(-1)
}

const service = process.argv[2]
const task = process.argv[3]

verify(service, task, async (inputs, outputs) => inputs.a + inputs.b === outputs)

console.log('verifier listening...')
